disabled_rules:
  - cyclomatic_complexity
  - identifier_name
  - multiple_closures_with_trailing_closure
  - nesting
  - type_name
  - unused_closure_parameter

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - Pods
  - "**/*.pb.swift" # exclude files with a wildcard

line_length: 300
type_body_length:
  - 600

function_body_length:
  - 150

file_length:
  warning: 800

reporter: "xcode"
