name: example2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_web_bluetooth: ^0.0.6+2
  get: 4.6.1
  flutter_reactive_ble:
    path: ../packages/flutter_reactive_ble
  reactive_ble_web:
    path: ../packages/reactive_ble_web

dev_dependencies:
  build_runner: ^2.1.4
  dependency_validator: ^3.1.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2

dependency_overrides:

flutter:
  uses-material-design: true
