name: ktlint
on: [pull_request]
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master